datagrid:
    issues-grid:
        source:
            type: orm
            acl_resource: oro_issue_view
            query:
                select:
                    - issue.id
                    - issue.code
                    - issue.summary
                    - issue.issueType
                    - priority.label as priorityLabel
                    - resolution.label as resolutionLabel
                    - assignee.id as assigneeId
                    - CONCAT(assignee.firstName, CONCAT(' ', assignee.lastName)) as assigneeName
                    - reporter.id as reporterId
                    - CONCAT(reporter.firstName, CONCAT(' ', reporter.lastName)) as reporterName
                    - issue.createdAt
                    - issue.updatedAt
                from:
                    - { table: %oro_issue.issue.entity.class%, alias: issue }
                join:
                    left:
                        - { join: issue.priority, alias: priority }
                        - { join: issue.resolution, alias: resolution }
                        - { join: issue.assignee, alias: assignee }
                        - { join: issue.reporter, alias: reporter }
        columns:
            code:
                label: oro.issue.code.label
            summary:
                label: oro.issue.summary.label
            issueType:
                label: oro.issue.issue_type.label
            priorityLabel:
                label: oro.issue.priority.label
            resolutionLabel:
                label: oro.issue.resolution.label
            reporterName:
                label: oro.issue.reporter.label
                type:  twig
                frontend_type: html
                template: OroIssueBundle:Issue:Datagrid/Property/reporter.html.twig
            assigneeName:
                label: oro.issue.assignee.label
                type:  twig
                frontend_type: html
                template: OroIssueBundle:Issue:Datagrid/Property/assignee.html.twig
            createdAt:
                label: oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label: oro.ui.updated_at
                frontend_type: datetime
        sorters:
            columns:
                summary:
                    data_name: issue.summary
                code:
                    data_name: issue.code
                createdAt:
                    data_name: issue.createdAt
                updatedAt:
                    data_name: issue.updatedAt
                priorityLabel:
                    data_name: issue.priority.priority
            default:
                updatedAt: DESC
        filters:
            columns:
                summary:
                    type:      string
                    data_name: issue.summary
                createdAt:
                    type:      datetime
                    data_name: issue.createdAt
                updatedAt:
                    type:      datetime
                    data_name: issue.updatedAt
        properties:
            id: ~
            view_link:
                type:       url
                route:      oro_issue_view
                params:     [ id ]
            update_link:
                type:       url
                route:      oro_issue_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      oro_api_delete_issue
                params:     [ id ]
        actions:
            view:
                type:          navigate
                acl_resource:  oro_issue_view
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  oro_issue_create
                label:         oro.grid.action.update
                icon:          edit
                link:          update_link
                rowAction:     true
            delete:
                type:          delete
                acl_resource:  oro_issue_delete
                label:         oro.grid.action.delete
                icon:          trash
                link:          delete_link
                rowAction:     true
        options:
            export:
                csv: { label: oro.grid.export.csv }

    user-issues-grid:
        extends: issues-grid
        source:
            query:
                where:
                    and:
                        - (assignee.id = :id OR reporter.id = :id)
            bind_parameters:
                - id
        options:
            toolbarOptions:
                pageSize:
                    default_per_page: 10
