oro_menu_config:
    items:
        issues_tab:
            label: 'oro.issue.menu.issues_tab.label'
            uri: '#'
            extras:
                position: 15
                icon: icon-puzzle-piece

        issues_divider:
            label: ''
            extras:
                position: 100
            attributes:
                class: 'divider'

        manage_issues:
            label: 'oro.issue.menu.manage_issues.label'
            route: 'oro_issue_index'
            extras:
                position: 105
                routes: ['oro_issue_index', 'oro_issue_update', 'oro_issue_create', 'oro_issue_view']
            attributes:
                class: 'mobile-hide'

    tree:
        application_menu:
            children:
                issues_tab:
                    children:
                        issues_divider: ~
                        manage_issues: ~

oro_titles:
    oro_issue_index:  ~
    oro_issue_view:   '%%entity.code%%'
    oro_issue_create: 'Create issue'
    oro_issue_update: '%%entity.code%% - Edit'

oro_navigation_elements:
    pinButton:
        routes:
            oro_issue_create: false
            oro_issue_update: false
