Oro\Bundle\IssueBundle\Entity\Issue:
    alias:                          oro_issue
    title_fields:                   [code]
    route:
        name:                       oro_issue_view
        parameters:
            id:                     id
    search_template:                OroIssueBundle:Search:result.html.twig
    fields:
        -
            name:                   code
            target_type:            text
            target_fields:          [code]
        -
            name:                   description
            target_type:            text
            target_fields:          [description]
        -
            name:                   summary
            target_type:            text
            target_fields:          [summary]
