parameters:
#    oro_issue.example.class: Oro\Bundle\IssueBundle\Example

services:
#    oro_issue.example:
#        class: %oro_issue.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
