parameters:
    oro_issue.issue.entity.class: Oro\Bundle\IssueBundle\Entity\Issue

services:
#    oro_issue.example:
#        class: %oro_issue.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
