Oro\IssueBundle\Entity\Issue:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            { fields: code, message: 'issue.validators.code_in_use' }
        - Oro\Bundle\IssueBundle\Validator\Constraints\IssueParent:
            { fields: issueType, message: 'issue.validators.parent_only_for_subtask' }
    properties:
        code:
            - NotBlank: ~
        summary:
            - NotBlank: ~
            - Length:
                max: 255
        description:
            - NotBlank: ~
        createdAt:
            - DateTime: ~
        updatedAt:
            - DateTime: ~
        priority:
            - NotBlank: ~
        resolution:
            - NotBlank: ~
        issueType:
            - NotBlank: ~
            - Oro\Bundle\IssueBundle\Validator\Constraints\IssueParentValidator: ~
        reporter:
            - NotBlank: ~
        assignee:
            - NotBlank: ~
