workflows:
    oro_issue_workflow:
        label: "Issue Processing Flow"
        entity: Oro\Bundle\IssueBundle\Entity\Issue
        start_step: open
        steps_display_ordered: true
        steps:
            open:
                label: 'Open'
                order: 10
                allowed_transitions:
                    - start_progress
                    - resolve
                    - close
            in_progress:
                label: 'In progress'
                order: 20
                allowed_transitions:
                    - stop_progress
                    - resolve
                    - close
            resolved:
                label: 'Resolved'
                order: 30
                allowed_transitions:
                    - reopen
                    - close
            closed:
                label: 'Closed'
                order: 40
                allowed_transitions:
                    - reopen

        transitions:
            start_progress:
                label: 'Start progress'
                step_to: in_progress
                frontend_options:
                    icon: 'icon-play'
                transition_definition: start_progress_definition
            stop_progress:
                label: 'Stop progress'
                step_to: open
                frontend_options:
                    icon: 'icon-stop'
                transition_definition: stop_progress_definition
            resolve:
                label: 'Resolve'
                step_to: resolved
                frontend_options:
                    icon: 'icon-ok'
                transition_definition: resolve_definition
            close:
                label: 'Close'
                step_to: closed
                frontend_options:
                    icon: 'icon-ok'
                transition_definition: closed_definition
            reopen:
                label: 'Reopen'
                step_to: open
                frontend_options:
                    icon: 'icon-repeat'
                transition_definition: reopen_definition

        transition_definitions:
            start_progress_definition: ~
            stop_progress_definition: ~
            resolve_definition: ~
            closed_definition: ~
            reopen_definition: ~
